author: Xiaokang Li
title: Xiaokang Li's Blog
email: xiaokangli616@gmail.com
description: >- 
  I am a software developer in fullstack but majority in Backend, I like cooking, baking and anything else to make people happy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.xiaokli.top"
github_username:  xiaokli
linkedin_username: xiaokang-li
facebook_username: xiaokangli616
# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfilec
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
