author: Xiaokang Li
title: 油条不紊
email: xiaokangli616@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.xiaokli.top"
github_username:  xiaokli
facebook_username: xiaokangli616
twitter_username: xiaokangli616
linkedin_username: xiaokang-li
# Build settings
plugins:
  - jekyll-feed

collections_dir: collects

collections:
  recipes:
    output: true
# ga
# google_analytics: G-51LZE9Z6N2

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfilec
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
